### ISSUE TITLE
Manual de proyecto

### ISSUE THREAD

**Issue by dylanalvarez** [Taller-2/app-android#48]
Un manual del proyecto: quienes somos, que herramientas usamos, como nos dividimos/administramos, que pensamos como calendario, que eventualidades sucedieron, donde le pifiamos en la estimacion
Qué subestimamos y era un quilombo en realidad, bugs conocidos, cómo quedó la cosa
Cómo lo probabamos, workflow, testing, coverage, merge requests
Cómo usabamos git, issue tracking

Es un manual para los TRES repos

ver [manual](https://docs.google.com/document/d/1beiVoOduFfhgMuekZwSR3FcGdA3s68ZGfd4r9yZFVQk/edit#)

**Comment by lucaslavandeira** [comment]
We did it!
